pull_request_rules:
  - name: say hi on new contribution
    conditions:
      - base=main
    actions:
        comment:
          message: |
              Welcome to ccf-deadlines!
              We're delighted to have you onboard (p≧w≦q)
        label:
          add: ['updateconf']
        request_reviews:
          teams: "@ccfddl/approvers"
  - name: automatic merge for master when CI passes and 1 reviews
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=build
      - base=main
    actions:
      merge:
        method: merge
      label:
        add: ['status/LGT1']
      comment:
        message: |
          Great job!
