name: MergeCheck

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with: 
        node-version: '15.x'
    - name: Assemble yml files
      run: |
        mkdir -p public/conference && cd public/conference
        cat `find ../../conference -name '*.yml' -not -path '**/types.yml'` > allconf.yml
        cp ../../conference/types.yml .
        cd ../..
    - name: Install dependency and build
      run: |
        yarn install
        yarn build
    
